version: '3.8'
services:
  dev-db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: trello-db
  test-db:
    image: postgres:latest
    restart: always
    ports:
      - 5423:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: test-db